apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
  selector:
    app: iris-api # Selects pods with the label 'app: iris-api'
  ports:
  - port: 80
    targetPort: 80

